apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-slack-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-slack-bot
  template:
    metadata:
      labels:
        app: my-slack-bot
    spec:
      containers:
        - name: my-slack-bot
          image: "{{ .Values.my-slack-bot.image.repository }}:{{ .Values.my-slack-bot.image.tag }}"
          env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-slack-bot-secrets
                  key: slackToken
            - name: MONGO_URI
              value: "{{ .Values.my-slack-bot.mongoURI }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: my-slack-bot-config
