apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      serviceAccountName: argocd
      containers:
        - name: argocd
          image: argoproj/argocd:latest
          ports:
            - containerPort: 8080
          env:
            - name: ARGOCD_OPTS
              value: "--insecure"
