apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
  labels:
    app: argocd
spec:
  selector:
    app: argocd
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
