slack_app_token: ""
slack_bot_token: ""
mongo_uri: "mongodb://localhost:27017"  # Ensure this is correctly formatted
database_name: "cloudclimbers_db"
plugins:
  create:
    url: "http://localhost:8081/create"
    buttons:
      - text: "Create Environment"
        action_id: "create_environment"
  get:
    url: "http://localhost:8082/get"
    buttons:
      - text: "Get Environment Status"
        action_id: "get_environment_status"
  get_info:
    commands: | # вибрати, що нам потрібно. Обговорити, як передати змінні та як повернути до бота результат.
      kubectl get pods -n <namespace> -o wide
      kubectl describe pods -n <namespace>
      kubectl get all -n <namespace>
      kubectl get deployment <deployment-name> -n <namespace>
      kubectl describe deployment <deployment-name> -n <namespace>
      kubectl get events -n <namespace>
    buttons:
      - text: "Get advanced Environment Status"
        action_id: "get_adv_environment_status"
    hash:
      - type: "SHA-256"
      - value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" #Example, this is empty string
  delete:
    url: "http://localhost:8083/delete"
    buttons:
      - text: "Delete Environment"
        action_id: "delete_environment"
main_buttons:
  - text: "List Enabled Plugins"
    action_id: "list_enabled_plugins"
    emoji: ":rocket:"
  - text: "Help"
    action_id: "help"
    emoji: ":information_source:"    
