apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hns-blog.fullname" . }}
  labels:
    {{- include "hns-blog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hns-blog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hns-blog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | quote }}
              protocol: TCP
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/mydatabase"
        - name: client
          image: "{{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag }}"
          imagePullPolicy: {{ .Values.clientImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000  # any client's port
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}
