apiVersion: v1
kind: Service
metadata:
  name: {{ include "hns-blog.fullname" . }}
  labels:
    {{- include "hns-blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | quote | default "80" }}
      targetPort: {{ .Values.service.targetport | quote | default "8081" }}
      protocol: TCP
      name: http
  selector:
    {{- include "hns-blog.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
      protocol: TCP
  selector:
    app: mongo
