apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-v20-0-1
  namespace: wordpress-v20-0-1
spec:
  releaseName: wordpress-v20-0-1
  chart:
    spec:
      chart: wordpress
      version: 20.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: wordpress-v20-0-1
  interval: 5m0s
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: wordpress-v20-0-1.cloudclimbers.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
