apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helmrelease-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: cloudclimbers
roleRef:
  kind: ClusterRole
  name: helmrelease-reader
  apiGroup: rbac.authorization.k8s.io
