apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: podinfo
resources:
  - ../base/podinfo
  - ../base/wordpress
  - ../base/wordpress-v22-0-0
#patches:
#  - path: podinfo-values.yaml
#    target:
#      kind: HelmRelease

patchesStrategicMerge:
  - podinfo-values.yaml
  - wordpress-values.yaml
  - wordpress-values-v22-0-0.yaml
