apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-v20-0-1
  namespace: wordpress-v20-0-1
spec:
  values:
    ingress:
      hosts:
        - host: wordpress-v20-0-1.cloudclimbers.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
