# values.yaml

# MongoDB configuration
mongodb:
  databaseName: cloudclimbers_db
  replicaCount: 3
  arbiter:
    enabled: false
  auth:
    enabled: false
  storage:
    size: 10Gi
    storageClassName: standard    
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: "4Gi"
  credentials:
    username: ""
    password: ""

# Slack Bot configuration
slackBot:
  image: gcr.io/slack-id/cloudclimbers-slack-bot:latest
  slackBotToken: ""
  slackAppToken: ""
  mongoUri: "mongodb://mongodb:27017/"
  mongoDatabaseName: "cloudclimbers_db"

# Plugin configuration
plugins:
  create:
    image: gcr.io/slack-id/cloudclimbers-slack-bot-create-plugin:latest
    url: "http://create:8081/create"
  get:
    image: gcr.io/slack-id/cloudclimbers-slack-bot-get-plugin:latest
    url: "http://get:8082/get"
  delete:
    image: gcr.io/slack-id/cloudclimbers-slack-bot-delete-plugin:latest
    url: "http://delete:8083/delete"

# GCP Service Account
gcpServiceAccount:
  enabled: true
  secretName: gcp-service-account-key
  encryptionPassword: ""

# GCP Service Account
botConfig:
  enabled: true
  secretName: slack-bot-config
  encryptionPassword: ""

# ArgoCD configuration
argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
