on:
  push:
    branches:
      - 'GitHub_actions'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.0.0
      - name: Initialize Go
        run: make go-init
      - name: Install dependencies
        run: make deps
      - name: Create the build
        run: make build
      - name: Run tests
        run: make test
      - name: Build Docker image
        run: make docker-build
      - name: Helm install
        run: make helm-install
      - name: Helm upgrade
        run: make helm-upgrade

